# Generated by Django 4.1.2 on 2023-01-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followings',
        ),
    ]
